import Head from 'next/head';
import Footer from '../src/components/Footer/Footer';
import Forecast from '../src/containers/Forecast/ForeCast';
import LocationInput from '../src/containers/LocationInput/LocationInput';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> Welcome to the <br /><span className="title">Weather App</span></h1>
        <p className="instructions">To use, simply enter a location on the input below and click the button or press 'enter' and the field should populate.</p>
        <LocationInput />
        <Forecast />
        <Footer />
      </main>
    </div>
  )
};
