import Head from 'next/head';
import Footer from '../components/Footer/Footer';
import Forecast from '../containers/Forecast/ForeCast';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> Welcome to <span className="title">Weather App</span></h1>
      </main>
      <Forecast />
      <Footer />
    </div>
  )
};
